server.port=8081
spring.application.name=demo

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/ticketwave1
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Event Bus: inmemory | rabbitmq
eventbus.type=inmemory

# RabbitMQ (used when eventbus.type=rabbitmq)
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest


#docker run -d --name ticketwave-rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:4-management

