-- =============================================================================
-- TicketWave — PostgreSQL Schema
-- Complete DDL for all domain entities
-- =============================================================================

-- ── ENUMS ───────────────────────────────────────────────────────────────────

CREATE TYPE user_role AS ENUM ('CUSTOMER', 'ORGANIZER', 'ADMIN');

CREATE TYPE event_status AS ENUM ('DRAFT', 'PUBLISHED', 'POSTPONED', 'CANCELLED', 'COMPLETED');

CREATE TYPE event_category AS ENUM ('CONCERT', 'SPORTS', 'CONFERENCE', 'THEATER', 'FESTIVAL', 'OTHER');

CREATE TYPE order_status AS ENUM ('PENDING', 'CONFIRMED', 'CANCELLED', 'REFUNDED');

CREATE TYPE payment_status AS ENUM ('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED');

CREATE TYPE payment_method AS ENUM ('CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER', 'DIGITAL_WALLET');

CREATE TYPE ticket_status AS ENUM ('VALID', 'USED', 'CANCELLED', 'REFUNDED');

CREATE TYPE promotion_scope AS ENUM ('NATIONAL', 'VENUE');

-- ── USERS ───────────────────────────────────────────────────────────────────

CREATE TABLE users (
    id              BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(255)    NOT NULL,
    password_hash   VARCHAR(255)    NOT NULL,
    first_name      VARCHAR(255)    NOT NULL,
    last_name       VARCHAR(255)    NOT NULL,
    phone           VARCHAR(255),
    role            user_role       NOT NULL DEFAULT 'CUSTOMER',
    enabled         BOOLEAN         NOT NULL DEFAULT TRUE,
    created_at      TIMESTAMP       NOT NULL,
    updated_at      TIMESTAMP
);

ALTER TABLE users ADD CONSTRAINT uq_users_email UNIQUE (email);

CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_role ON users (role);

COMMENT ON TABLE users IS 'Registered users: customers, organizers, and admins';
COMMENT ON COLUMN users.password_hash IS 'BCrypt-encoded password hash';

-- ── VENUES ──────────────────────────────────────────────────────────────────

CREATE TABLE venues (
    id                     BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   VARCHAR(255)    NOT NULL,
    city                   VARCHAR(255)    NOT NULL,
    address                VARCHAR(255)    NOT NULL,
    capacity               INTEGER         NOT NULL,
    has_assigned_seating   BOOLEAN         NOT NULL,
    created_at             TIMESTAMP       NOT NULL,
    updated_at             TIMESTAMP
);

CREATE INDEX idx_venues_city ON venues (city);
CREATE INDEX idx_venues_name ON venues (name);

COMMENT ON TABLE venues IS 'Event venues with optional assigned seating';

-- ── SECTIONS ────────────────────────────────────────────────────────────────

CREATE TABLE sections (
    id                     BIGINT          GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id               BIGINT          NOT NULL REFERENCES venues(id) ON DELETE CASCADE,
    name                   VARCHAR(255)    NOT NULL,
    capacity               INTEGER         NOT NULL,
    is_general_admission   BOOLEAN         NOT NULL,
    created_at             TIMESTAMP       NOT NULL,
    updated_at             TIMESTAMP
);

CREATE INDEX idx_sections_venue_id ON sections (venue_id);

COMMENT ON TABLE sections IS 'Venue sections/areas (e.g. Floor, Balcony, VIP)';

-- ── SEATS ───────────────────────────────────────────────────────────────────

CREATE TABLE seats (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    section_id     BIGINT       NOT NULL REFERENCES sections(id) ON DELETE CASCADE,
    seat_row       VARCHAR(10)  NOT NULL,
    seat_number    INTEGER      NOT NULL,
    created_at     TIMESTAMP    NOT NULL,
    updated_at     TIMESTAMP
);

CREATE INDEX idx_seats_section_id ON seats (section_id);
CREATE INDEX idx_seats_row ON seats (section_id, seat_row, seat_number);

COMMENT ON TABLE seats IS 'Individual seats within a section (for assigned-seating venues)';

-- ── EVENTS ──────────────────────────────────────────────────────────────────

CREATE TABLE events (
    id                BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    venue_id          BIGINT           NOT NULL REFERENCES venues(id),
    name              VARCHAR(255)     NOT NULL,
    description       TEXT,
    category          event_category   NOT NULL,
    status            event_status     NOT NULL DEFAULT 'DRAFT',
    artist            VARCHAR(255),
    event_date        TIMESTAMP        NOT NULL,
    sales_start_date  TIMESTAMP,
    sales_end_date    TIMESTAMP,
    created_at        TIMESTAMP        NOT NULL,
    updated_at        TIMESTAMP
);

CREATE INDEX idx_events_artist     ON events (artist);
CREATE INDEX idx_events_date       ON events (event_date);
CREATE INDEX idx_events_status     ON events (status);
CREATE INDEX idx_events_venue_id   ON events (venue_id);
CREATE INDEX idx_events_category   ON events (category);
-- Composite index for common search: published events by date
CREATE INDEX idx_events_published_date ON events (event_date) WHERE status = 'PUBLISHED';

COMMENT ON TABLE events IS 'Events with status lifecycle: DRAFT → PUBLISHED → POSTPONED/CANCELLED/COMPLETED';
COMMENT ON COLUMN events.description IS 'Full event description in plain text';

-- ── TICKET TYPES ───────────────────────────────────────────────────────────

CREATE TABLE ticket_types (
    id               BIGINT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id         BIGINT            NOT NULL REFERENCES events(id) ON DELETE CASCADE,
    section_id       BIGINT            REFERENCES sections(id),
    name             VARCHAR(255)      NOT NULL,
    price            DECIMAL(10, 2)    NOT NULL,
    total_quantity   INTEGER           NOT NULL,
    sold_quantity    INTEGER           NOT NULL DEFAULT 0,
    created_at       TIMESTAMP         NOT NULL,
    updated_at       TIMESTAMP
);

CREATE INDEX idx_ticket_types_event_id   ON ticket_types (event_id);
CREATE INDEX idx_ticket_types_section_id ON ticket_types (section_id);

COMMENT ON TABLE ticket_types IS 'Ticket categories/prices for an event (e.g. General Admission, VIP, Front Row)';
COMMENT ON COLUMN ticket_types.sold_quantity IS 'Atomically incremented/decremented for inventory control';
COMMENT ON COLUMN ticket_types.total_quantity IS 'Total tickets available for this type';

-- ── ORDERS ──────────────────────────────────────────────────────────────────

CREATE TABLE orders (
    id               BIGINT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT            NOT NULL REFERENCES users(id),
    order_number     UUID              NOT NULL,
    status           order_status      NOT NULL DEFAULT 'PENDING',
    total_amount     DECIMAL(10, 2)    NOT NULL,
    promotion_code   VARCHAR(255),
    discount_amount  DECIMAL(10, 2),
    created_at       TIMESTAMP         NOT NULL,
    updated_at       TIMESTAMP
);

ALTER TABLE orders ADD CONSTRAINT uq_orders_order_number UNIQUE (order_number);

CREATE INDEX idx_orders_user_id      ON orders (user_id);
CREATE INDEX idx_orders_status       ON orders (status);
CREATE INDEX idx_orders_order_number ON orders (order_number);
CREATE INDEX idx_orders_created_at   ON orders (created_at);

COMMENT ON TABLE orders IS 'Purchase orders with lifecycle: PENDING → CONFIRMED → CANCELLED/REFUNDED';
COMMENT ON COLUMN orders.order_number IS 'Public-facing UUID order identifier';

-- ── ORDER ITEMS ─────────────────────────────────────────────────────────────

CREATE TABLE order_items (
    id               BIGINT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id         BIGINT            NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    ticket_type_id   BIGINT            NOT NULL REFERENCES ticket_types(id),
    seat_id          BIGINT            REFERENCES seats(id),
    unit_price       DECIMAL(10, 2)    NOT NULL,
    created_at       TIMESTAMP         NOT NULL,
    updated_at       TIMESTAMP
);

ALTER TABLE order_items
    ADD CONSTRAINT uq_order_items_ticket_type_seat
    UNIQUE (ticket_type_id, seat_id);

CREATE INDEX idx_order_items_order_id       ON order_items (order_id);
CREATE INDEX idx_order_items_ticket_type_id ON order_items (ticket_type_id);
CREATE INDEX idx_order_items_seat_id        ON order_items (seat_id);

COMMENT ON TABLE order_items IS 'Individual line items within an order';
COMMENT ON COLUMN order_items.seat_id IS 'NULL for general-admission tickets';

-- ── PAYMENTS ───────────────────────────────────────────────────────────────

CREATE TABLE payments (
    id                       BIGINT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id                 BIGINT            NOT NULL UNIQUE REFERENCES orders(id),
    external_transaction_id  VARCHAR(255),
    amount                   DECIMAL(10, 2)    NOT NULL,
    method                   payment_method    NOT NULL,
    status                   payment_status    NOT NULL DEFAULT 'PENDING',
    paid_at                  TIMESTAMP,
    refunded_at              TIMESTAMP,
    created_at               TIMESTAMP         NOT NULL,
    updated_at               TIMESTAMP
);

CREATE INDEX idx_payments_order_id ON payments (order_id);
CREATE INDEX idx_payments_status  ON payments (status);

COMMENT ON TABLE payments IS 'Payment transactions linked one-to-one with orders';
COMMENT ON COLUMN payments.external_transaction_id IS 'ID from external payment gateway (stubbed)';

-- ── TICKETS ─────────────────────────────────────────────────────────────────

CREATE TABLE tickets (
    id               BIGINT           GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_item_id    BIGINT           NOT NULL UNIQUE REFERENCES order_items(id),
    ticket_code      UUID             NOT NULL,
    status           ticket_status    NOT NULL DEFAULT 'VALID',
    issued_at        TIMESTAMP        NOT NULL,
    validated_at     TIMESTAMP,
    created_at       TIMESTAMP        NOT NULL,
    updated_at       TIMESTAMP
);

ALTER TABLE tickets ADD CONSTRAINT uq_tickets_ticket_code UNIQUE (ticket_code);

CREATE INDEX idx_tickets_ticket_code   ON tickets (ticket_code);
CREATE INDEX idx_tickets_status        ON tickets (status);
-- Supports query: find tickets by user (join via order_items → orders)
CREATE INDEX idx_tickets_order_item_id ON tickets (order_item_id);

COMMENT ON TABLE tickets IS 'Digital tickets issued per order item after payment confirmation';
COMMENT ON COLUMN tickets.ticket_code IS 'Unique UUID for ticket QR code / barcode';
COMMENT ON COLUMN tickets.validated_at IS 'Timestamp when ticket was scanned at entry';

-- ── PROMOTIONS ──────────────────────────────────────────────────────────────

CREATE TABLE promotions (
    id                   BIGINT            GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code                 VARCHAR(255)      NOT NULL,
    description          TEXT,
    scope                promotion_scope   NOT NULL,
    venue_id             BIGINT            REFERENCES venues(id),
    discount_percentage  DECIMAL(5, 2),
    discount_flat        DECIMAL(10, 2),
    max_uses             INTEGER           NOT NULL,
    current_uses         INTEGER           NOT NULL DEFAULT 0,
    valid_from           TIMESTAMP         NOT NULL,
    valid_until          TIMESTAMP         NOT NULL,
    active               BOOLEAN           NOT NULL DEFAULT TRUE,
    created_at           TIMESTAMP         NOT NULL,
    updated_at           TIMESTAMP
);

ALTER TABLE promotions ADD CONSTRAINT uq_promotions_code UNIQUE (code);

CREATE INDEX idx_promotions_code      ON promotions (code) WHERE active = TRUE;
CREATE INDEX idx_promotions_venue_id  ON promotions (venue_id);
CREATE INDEX idx_promotions_scope     ON promotions (scope);
CREATE INDEX idx_promotions_validity  ON promotions (valid_from, valid_until);

COMMENT ON TABLE promotions IS 'Discount promotions: percentage or flat, national or venue-scoped';
COMMENT ON COLUMN promotions.discount_percentage IS 'Discount percentage (e.g. 15.00 for 15%%)';
COMMENT ON COLUMN promotions.discount_flat IS 'Flat discount amount in currency units';

-- ── SCHEMA MIGRATION TABLE ──────────────────────────────────────────────────

CREATE TABLE schema_version (
    version          INTEGER       NOT NULL PRIMARY KEY,
    description      VARCHAR(255)  NOT NULL,
    applied_at       TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO schema_version (version, description) VALUES
    (1, 'Initial schema: all domain tables, enums, indexes, constraints');
